// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWz237nFj8kKGEaAJtyu5Ukl1qbGF7ZM',
    appId: '1:940367622760:web:06773f095e8ecc4f6781dd',
    messagingSenderId: '940367622760',
    projectId: 'la-fleur-715a3',
    authDomain: 'la-fleur-715a3.firebaseapp.com',
    storageBucket: 'la-fleur-715a3.appspot.com',
    measurementId: 'G-RN99WR56PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzQdIeUsvYOuWgCr1-zmmjiFU7_QVMPs',
    appId: '1:940367622760:android:67b37571b4c2ea1c6781dd',
    messagingSenderId: '940367622760',
    projectId: 'la-fleur-715a3',
    storageBucket: 'la-fleur-715a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz8o_v1gS1KvIjb_9NM48ybYTb4B7NaPQ',
    appId: '1:940367622760:ios:24a982900fa5258b6781dd',
    messagingSenderId: '940367622760',
    projectId: 'la-fleur-715a3',
    storageBucket: 'la-fleur-715a3.appspot.com',
    iosClientId: '940367622760-t4oq6f5l8d75dms927nujcdarh9aj671.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz8o_v1gS1KvIjb_9NM48ybYTb4B7NaPQ',
    appId: '1:940367622760:ios:24a982900fa5258b6781dd',
    messagingSenderId: '940367622760',
    projectId: 'la-fleur-715a3',
    storageBucket: 'la-fleur-715a3.appspot.com',
    iosClientId: '940367622760-t4oq6f5l8d75dms927nujcdarh9aj671.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
